### ISSUE TITLE
您好，我下载了MSMO数据集，data19.zip好像坏了，我在windows和linux上均无法解压他。我尝试重新下载过data19，都解压不了。能重新上传一遍data19吗

### ISSUE THREAD

**Issue by Zhangkaixiongyyds** [ZNLP/ZNLP-Dataset#1]

**Comment by Zhangkaixiongyyds** [comment]
用WinRAR无法解压data19，我尝试下载了360压缩工具解压data19并解压成功了

**Comment by duyanhedyh** [comment]
> 用WinRAR无法解压data19，我尝试下载了360压缩工具解压data19并解压成功了

data1.zip在Windos可以打开，上传到Linux后，进行MD5验证，文件是一样的，但是Linux无法解压，报错：文件有损坏，您是否遇到过？

**Comment by Zhujunnan** [comment]
可能是网络的原因，重新下载试试呢？

**Comment by duyanhedyh** [comment]
> 可能是网络的原因，重新下载试试呢？

test_data和valid_data里面的数据放混乱了吧。统计的和论文显示的数目不一样。

**Comment by Zhujunnan** [comment]
麻烦再检查一下吧，跟很多使用过这个数据集的同学确认了一下，都没有出现过这个问题呢。
