### ISSUE TITLE
《MSMO》的数据集中是否包含人工挑选和评分的内容？

### ISSUE THREAD

**Issue by bigbrother001** [ZNLP/ZNLP-Dataset#2]
您好，感谢您在多模态领域所做的如此多的工作。
我想请问一下，《MSMO》这篇论文中，4.1节提到的为每个summary人工挑选了图片，4.4节提到的计算相关系数所使用的人工评分，这两部分数据怎样可以得到？

**Comment by Zhujunnan** [comment]
您好，目前开源的数据并不包含人工评分。如果需要计算相关系数，通常还是需要重新开展人工实验的，毕竟人工实验并不适合迁移。
